name: "Build & Release Extension"

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  push:
    tags:
      - '*'

jobs:
  Build-VSIX-File:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v6

      - name: Setup node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Build Package
        run: vsce package 

      - name: Find Extension Version
        id: findVersion
        run: |
          APP_VERSION=`cat package.json | jq ".version" -M | sed 's/\"//g'`
          echo "name=AppVersion::$APP_VERSION" >> $GITHUB_OUTPUT
          echo "app version = v$APP_VERSION"
      
      # - name: Publish extension package
      #   env:
      #     VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
      #   run: npm run vsce -- publish -p $VSCODE_MARKETPLACE_TOKEN

      - uses: actions/upload-artifact@v7
        name: Upload artifact
        with:
          name: wresl-highlight-${{ steps.findVersion.outputs.AppVersion }}.vsix
          path: wresl-highlight-${{ steps.findVersion.outputs.AppVersion }}.vsix
